<?php
defined('BASEPATH') OR exit('No direct script access allowed');

const GET_ADMIN_TYPE_LOGIN_PASSWORD = 1;

const GET_BLOG_TYPE_LIST_BY_POST_ORDER_BY_TIME = 1;
const GET_BLOG_TYPE_LIST_BY_TAG_ORDER_BY_TIME = 2;
const GET_BLOG_TYPE_BY_ARTICLE_ID = 3;


const POST_BLOG_TYPE_ADD_ARTICLE = 1;
const POST_BLOG_TYPE_ADD_COMMENT = 2;